# Generated by Django 5.0.4 on 2024-05-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0002_delete_vezba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vezba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=256)),
                ('opis', models.CharField(max_length=10000)),
                ('program', models.IntegerField()),
            ],
        ),
    ]
