# Generated by Django 5.0.4 on 2024-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0004_rename_program_vezba_grupa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaKoVezba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_vezbanja', models.IntegerField()),
            ],
        ),
    ]
